### ISSUE TITLE
android-19 error in webstorm/cordova runner

### ISSUE THREAD

**Issue by chovy** [keshavos/generator-angularjs-cordova#34]
```
Error: Please install Android target "android-19".
Hint: Run "android" from your command-line to open the SDK manager.
```

**Comment by keshavos** [comment]
Make sure to install and configure the android sdk on your machine. Check if you have Android 4.4.2(API 19) installed with `$> android sdk`. 
You can change the API version in AndroidManifest.xml. 
Cordova provides documentation regarding setting up a dev environment [here](http://cordova.apache.org/docs/en/5.0.0/guide_platforms_android_index.md.html#Android%20Platform%20Guide).
