### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by iDuuck** [keshavos/generator-angularjs-cordova#35]
Hey guys,
I am new to this cordova stuff but I have experience with Angular.js. Now I wanted to create a new project, but it is not possible to create it, because there is an error, when executing `grunt serve`.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```
Nothing more, nothing less. It's not able to find cordova.js in the projects root. Is this normal or what's going on there?

**Comment by daniloprates** [comment]
I'm having the same issue. It works fine in the IOS build, but not on `grunt serve`

**Comment by iDuuck** [comment]
@daniloprates I just saw, that this is normal for local development. It is able to be loaded on iOS but not on your browser. Everything fine.
