### ISSUE TITLE
The apk file when loaded on to mobile shows white screen

### ISSUE THREAD

**Issue by wagons24** [keshavos/generator-angularjs-cordova#36]
We created a module login. we added few files of login html, controller & routes in respective folders. then we created an apk file (the execution was success). but the apk file when loaded pushed a white screen. we then had a look at the www structure and the new module "login" was not copied under this directory. please help

**Comment by keshavos** [comment]
Did you run a `grunt build` before creating the apk?

**Comment by wagons24** [comment]
Yes. We resolved it... the ngmaterial was not defined in the config and we added it manually and is fine now.
Thanks for the help.

Date: Tue, 17 Mar 2015 01:25:32 -0700
