### ISSUE TITLE
Missing cordova.js reference

### ISSUE THREAD

**Issue by wedkarz** [keshavos/generator-angularjs-cordova#37]
I have done all steps following this page: https://www.npmjs.com/package/generator-angularjs-cordova#application-generator. Though when I inspect, there are console errors, specifically missing cordova library. 

Failed to load resource: the server responded with a status of 404 (Not Found) http://192.168.2.2:9000/cordova.js 

How can I handle the problem? (I'm new to things like bower, npm, gulp, grunt)

**Comment by m3ftah** [comment]
I have the same problem!

**Comment by wedkarz** [comment]
In my case it was because I was running just web app. But it need to be prepared for specific platform i.e. cordova build android, so that cordova library links to platform specific implementation.

**Comment by m3ftah** [comment]
Ah, okey, thanks :+1:

**Comment by keshavos** [comment]
Correct. This is as expected when you serve the app from within the `www/` as it does not contain the `cordova.js`. Cordova build task copies the `cordova.js` to the platform specific directory. 
Reason why it's referenced in the `index.html` is to prevent developers forgetting to add this, in which case you wouldn't be able to access any cordova functionality.!
