### ISSUE TITLE
Loading Cordova Plugins

### ISSUE THREAD

**Issue by julesmoretti** [keshavos/generator-angularjs-cordova#39]
Hello Keshavos:

So far this has been one of the most comprehensive and seamless generator I have landed on.

I am having difficulty though implementing cordova plugins.

Plugin I am trying to get working in this exemple is `statusBar`.

ran the following:
`cordova plugin add cordova-plugin-statusbar`

Then checked using
`cordova plugins ls`
`cordova-plugin-statusbar 1.0.0 "StatusBar"`

Then in my controller I have tried:

```
angular
    .module('core')
    .controller('HomeController', ['$scope', function($scope) {

        window.cordova.StatusBar.overlaysWebView(true);
        window.cordova.StatusBar.hide();
```
or 
```
angular
    .module('core')
    .controller('HomeController', ['$scope', function($scope) {

        StatusBar.overlaysWebView(true);
        StatusBar.hide();
```
or 
```
angular
    .module('core')
    .controller('HomeController', ['$scope', function($scope) {

        window.StatusBar.overlaysWebView(true);
        window.StatusBar.hide();
```
or 
```
angular
    .module('core')
    .controller('HomeController', ['$scope', function($scope) {

        cordova.StatusBar.overlaysWebView(true);
        cordova.StatusBar.hide();
```

Similarly I tried passing the plugin in the controller with no success:

```
angular
    .module('core')
    .controller('HomeController', 'StatusBar', ['$scope', function($scope, StatusBar) {
```
or like this:
```
angular
    .module('core')
    .controller('HomeController', ['$scope', function($scope, StatusBar) {
```

Could you shine some light on how to get these up and running?

That would be so valuable for me please.

Thank you for your time and love what you started keep it up.

Cheers.

Jules

**Comment by julesmoretti** [comment]
So silly. Just needed to wrap it around:

```
        document.addEventListener("deviceready", onDeviceReady, false);

        function onDeviceReady() {
            // Now safe to use device APIs
            StatusBar.hide();
        }
```

And no need to pass anything in the controller at all. Sorry about that.

**Comment by keshavos** [comment]
Glad you figured it out @julesmoretti 
As a suggestion, I would recommend checking out [ngcordova](http://ngcordova.com/) which helps keep accessing cordova features through angular services. That way, keeps all logic within Angular.
Just my two cents. :)
