### ISSUE TITLE
Splash screen images are being added in cordova build

### ISSUE THREAD

**Issue by wagons24** [keshavos/generator-angularjs-cordova#42]
The splash screen is showing blank screen and images are not added in the splashscreen. Also, the changes made to config.xml to add the splashscreen is lost when we execute the command
`cordova build android`

Please help... it is on priority

**Comment by keshavos** [comment]
Hi  @wagons24 , 
Try the following steps to get the splashscreens working:
- install the [cordova splashscreen plugin](http://plugins.cordova.io/#/package/org.apache.cordova.splashscreen)
- add the following to your `config.xml`:
```
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="5000" />
    <platform name="android">
        <!-- you can use any density that exists in the Android project -->
        <splash src="res/drawable-land-hdpi/screen.png" density="land-hdpi" />
        <splash src="res/drawable-land-ldpi/screen.png" density="land-ldpi" />
        <splash src="res/drawable-land-mdpi/screen.png" density="land-mdpi" />
        <splash src="res/drawable-land-xhdpi/screen.png" density="land-xhdpi" />
        <splash src="res/splash-port-hdpi/screen.png" density="port-hdpi" />
        <splash src="res/splash-port-ldpi/screen.png" density="port-ldpi" />
        <splash src="res/splash-port-mdpi/screen.png" density="port-mdpi" />
        <splash src="res/splash-port-xhdpi/screen.png" density="port-xhdpi" />
    </platform>
```
- Replace the default cordova icons and splashscreens in `/platforms/android/res/drawable-land-*` (landscape) and `/platforms/android/res/drawable-port-*`. 
- Make sure the filenames you specify in `config.xml` exist in the specified folder.

The `SplashScreenDelay` value is to specify how long the splashscreen should display on app launch. 
More info & documentation [here](http://cordova.apache.org/docs/en/5.0.0/config_ref_images.md.html#Icons%20and%20Splash%20Screens)

**Comment by wagons24** [comment]
Hi,
Thanks for the response,
When we try to install the cordova splashscreen plugin, we get an error saying the cordova version is 3.5.0 and needs to be upgraded to 3.6.0 and we are not able to find the steps to upgrade the cordova to the latest version.Please help
Thanks,

Date: Mon, 8 Jun 2015 02:33:55 -0700

**Comment by keshavos** [comment]
`npm info cordova` - Lists info about the package including the available versions
To install a cordova version
`npm install cordova@3.6.3-0.2.13` or `npm install -g cordova@3.6.3-0.2.13` (to update cordova globally)

Cordova website has documentation regarding most of these generic tasks. Info about updating version can be found [here](https://cordova.apache.org/docs/en/3.6.0/guide_cli_index.md.html#The%20Command-Line%20Interface_updating_cordova_and_your_project)
