### ISSUE TITLE
Modules opted out of during setup still referenced as angular dependencies

### ISSUE THREAD

**Issue by aderowbotham** [keshavos/generator-angularjs-cordova#43]
If you choose not to include `ngCookies` during installation the installation still works but on running the app we get the dependency error:

    Uncaught Error: [$injector:modulerr] Failed to instantiate module angularjsapp due to:
    Error: [$injector:modulerr] Failed to instantiate module ngCookies due to:
    Error: [$injector:nomod] Module 'ngCookies' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

The workaround is to manually remove it from `applicationModuleVendorDependencies` in `app/js/config.js`.

Modules should not be added to the dependencies array if they are not chosen during setup.

**Comment by keshavos** [comment]
Thanks for the find.! This is fixed in the above commit.
